-- MoodSync scheduled reminders
--
-- What this function sends:
-- 1) Daily moment reminder: once per user per Prague day if no photo/video was uploaded.
-- 2) Daily thermometer reminder: once per user per Prague day if the user has not updated the thermometer/status today.
-- 3) 48h inactivity nudge: if the user has not updated status and has not posted anything for ~48h.
-- 4) 72h quiet-couple nudge: if the couple feed/chat has been quiet for ~72h.
--
-- Required first:
-- 1) Run supabase/engagement_reminders_setup.sql in Supabase SQL Editor.
-- 2) Deploy/update Edge Function mood-daily-reminder.
-- 3) Make sure these secrets exist:
--    VAPID_PUBLIC_KEY
--    VAPID_PRIVATE_KEY
--    VAPID_SUBJECT=mailto:your@email.cz
--    SUPABASE_URL
--    SUPABASE_SERVICE_ROLE_KEY
--
-- Required secret for scheduled calls:
-- npx supabase secrets set MOOD_REMINDER_SECRET="your-long-random-secret"
-- Call the function with header:
-- x-cron-secret: your-long-random-secret
--
-- Recommended schedule for the daily moment reminder:
-- Supabase Dashboard -> Edge Functions -> mood-daily-reminder -> Schedule
-- Run once daily at 10:30 Europe/Prague.
-- If Supabase asks for UTC cron, use 30 8 * * * during CEST (summer),
-- or 30 9 * * * during CET (winter).
--
-- You can also run it hourly; push_notification_log prevents duplicate daily/periodic nudges.
